# Name of website
title: "Synthwave '84"

description: >- # this means to ignore newlines until "baseurl:"
  "Synthwave '84 is a collection of themes created by CelestialReaver."
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CelestialReaver

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Your name to show in the footer
author: CelestialReaver

# --- List of links in the navigation bar --- #

navbar-links:
  BetterDiscord: "https://betterdiscord.app/theme/Synthwave%20%2784"
  Powercord: "https://github.com/CelestialReaver/Synthwave84-Powercord"
  Discord Web: "https://userstyles.org/styles/245597/synthwave-84"
  Author's home: "https://github.com/CelestialReaver"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "https://i.imgur.com/MA2fwa2.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
#permalink: /:year-:month-:day-:title/
#paginate: 5

kramdown:
  input: GFM

#exclude:
#  - CHANGELOG.md
#  - CNAME
#  - LICENSE
#  - README.md
  
relative_links:
  enabled: true
  collections: true
  
#include:
#- docs/
#- index.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-feed
